### ISSUE TITLE
Add structspeak & structanswer so we know how the bot learnt the thing?

### ISSUE THREAD

**Issue by Artoria2e5** [PeterCxy/telegram-bot-language-chinese#11]

**Comment by PeterCxy** [comment]
This is no longer under maintaince. See gotgbot.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.3.5&pv=5.1.1&source=email_footer_2] On Fri, Oct 02, 2015 at 9:05 PM, Mingye Wang < notifications@github.com [notifications@github.com] > wrote:
—
Reply to this email directly or view it on GitHub
[https://github.com/PeterCxy/telegram-bot-language-chinese/issues/11] .[https://github.com/notifications/beacon/AEUoxzt4py4o2fvUpoh8IGP3pSDH6Ds0ks5o3nhpgaJpZM4GH9F5.gif]

**Comment by Artoria2e5** [comment]
You should say that in README.md.
